drop table if exists articles;
CREATE TABLE articles (
  ID INT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  CATEGORY VARCHAR(50) NOT NULL,
  TAGS VARCHAR(100) NOT NULL,
  AUTHOR VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
) ;